name: skate
main: net.kgab0r.skate.skate
version: 1.1
author: kgab0r
website: http://kgab0r.net/
database: false

commands:
  is:
    description: IceSkate.
    permission: iceskate.op
 
permissions:
    iceskate.skate:
        description: Allow skate on ice